# Generated by Django 2.0.4 on 2018-10-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superdealzapp', '0002_auto_20180501_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodxlista',
            name='precio',
        ),
    ]
