# Generated by Django 2.0.9 on 2018-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdealzapp', '0004_auto_20181123_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
