# Generated by Django 2.0.9 on 2018-11-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superdealzapp', '0006_auto_20181123_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, upload_to='productos'),
        ),
    ]
